name: "Catho go auto coverage custom action"
description: "Action to run and comment the coverage test results"

inputs:
  github-token:
    description: "Github token to comment on PR"
    required: true

runs:
  using: "composite"
  steps:
      
      - name: Download detailed coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage.txt
      
      - name: Download total coverage 
        uses: actions/download-artifact@v2
        with:
          name: total-coverage-report
          path: coverage-total.txt

      - name: Comment on PR with test results
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          script: |
            const fs = require('fs');
            const coverageReport = fs.readFileSync(coverage.txt, 'utf8');
            const totalCoverageReport = fs.readFileSync(coverage-total.txt, 'utf8');

            const { data: comments } = await github.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const previousComment = comments.find(comment => comment.user.login === 'github-actions[bot]');

            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Coverage report \n\n <table> <th>' + totalCoverageReport + '</th> </table> \n\n <details><summary>Show covered files </summary> <br/> \n\n | Test Coverage Report | \n |------| \n' + coverageReport + '</details>'
            }

            if (previousComment) {
              return await github.issues.updateComment({
                comment_id: previousComment.id,
                ...comment
              });
            }
            
            await github.issues.createComment({
              issue_number: context.issue.number,
              ...comment
            });
